syntax = "proto3";

message Indicativos {
  repeated Registro records = 1;
}

message Registro {
  string tipo_identificacao = 1;
  string cnpj_ou_cpf = 2;
  string nome_entidade = 3;
  string fistel = 4;
  string servico = 5;
  string indicativo = 6;
  string coer = 7;
  string uf_entidade = 8;
  string numero_estacao = 9;
  string nome_estacao = 10;
  string tipo_estacao = 11;
  string frequencias_operacao = 12;
  string uf_estacao = 13;
  string municipio_estacao = 14;
  string data_primeiro_licenciamento = 15;
  string data_ultimo_licenciamento = 16;
  string data_validade_estacao = 17;
  string status_validade = 18;
}
